{{- if and .Values.siemConnectors.enabled .Values.siemConnectors.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.siemConnectors.serviceAccount.name | default "siem-connectors" }}
  labels:
    {{- include "siemConnectors.labels" . | nindent 4 }}
  {{- with .Values.siemConnectors.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
