{{- if and (eq (include "trustguard.enabled" .) "true") (eq (include "neuraltrust-platform.monitoring.enabled" .) "true") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trustguard
  labels:
    {{- include "neuraltrust-platform.monitoring.labels" . | nindent 4 }}
    {{- include "trustguard.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "trustguard.name" . }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ include "neuraltrust-platform.monitoring.interval" . }}
{{- end }}
