{{- if and .Values.enabled (eq (include "neuraltrust-platform.ha.pdbEnabled" (dict "ctx" . "local" .Values.podDisruptionBudget)) "true") (gt (.Values.replicaCount | int) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "neuraltrust-watchdog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neuraltrust-watchdog.labels" . | nindent 4 }}
spec:
  {{- include "neuraltrust-platform.ha.pdbSpec" (dict "ctx" . "local" .Values.podDisruptionBudget) | nindent 2 }}
  selector:
    matchLabels:
      {{- include "neuraltrust-watchdog.selectorLabels" . | nindent 6 }}
{{- end }}
