{{- if and .Values.enabled .Values.podDisruptionBudget.enabled (gt (.Values.replicaCount | int) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "neuraltrust-watchdog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neuraltrust-watchdog.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "neuraltrust-watchdog.selectorLabels" . | nindent 6 }}
{{- end }}
