{{- $authValue := .Values.server.authToken.value -}}
{{- if and (not .Values.server.authToken.existingSecret) $authValue }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neuraltrust-watchdog.authSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neuraltrust-watchdog.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.server.authToken.secretKey }}: {{ $authValue | b64enc | quote }}
---
{{- end }}
{{- $slackValue := .Values.actions.slack.webhookUrl -}}
{{- if and (not .Values.actions.slack.existingSecret) $slackValue }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neuraltrust-watchdog.slackSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neuraltrust-watchdog.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.actions.slack.secretKey }}: {{ $slackValue | b64enc | quote }}
{{- end }}
