{{- if and (eq (include "neuraltrust-platform.isV2" .) "true") (eq (include "neuraltrust-platform.isExternal" .) "true") }}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clickstack-otel-collector.serviceAccountName" . }}
  labels:
    {{- include "clickstack-otel-collector.labels" . | nindent 4 }}
  {{- $saAnn := include "neuraltrust-platform.serviceAccount.annotationsBlock" (dict "ctx" . "annotations" .Values.serviceAccount.annotations) }}
  {{- with $saAnn }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
