apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clickhouse.fullname" . }}-config
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
data:
  logging.xml: |
    <clickhouse>
      <logger>
        <level>{{ .Values.logLevel | default "warning" }}</level>
        <console>true</console>
      </logger>
      <listen_host>0.0.0.0</listen_host>
    </clickhouse>
