{{- if not .Values.auth.existingSecret }}
{{- $secretName := include "clickhouse.fullname" . }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and $existingSecret (hasKey $existingSecret.data "admin-password") }}
  admin-password: {{ index $existingSecret.data "admin-password" }}
  {{- else if .Values.auth.password }}
  admin-password: {{ .Values.auth.password | b64enc }}
  {{- else }}
  admin-password: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
{{- end }}
