{{- if and .Values.firewall.enabled .Values.firewall.gateway.autoscaling .Values.firewall.gateway.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: firewall
  labels:
    {{- include "firewall.gateway.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: firewall
  minReplicas: {{ .Values.firewall.gateway.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ .Values.firewall.gateway.autoscaling.maxReplicas | default 10 }}
  metrics:
    {{- if .Values.firewall.gateway.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.firewall.gateway.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.firewall.gateway.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.firewall.gateway.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
