{{- if and .Values.firewall.enabled .Values.firewall.autoscaling .Values.firewall.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: firewall
  labels:
    {{- include "firewall.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: firewall
  minReplicas: {{ .Values.firewall.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ .Values.firewall.autoscaling.maxReplicas | default 10 }}
  metrics:
  {{- if .Values.firewall.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.firewall.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.firewall.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.firewall.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
