{{- if and .Values.firewall.enabled .Values.firewall.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.firewall.serviceAccount.name | default "firewall" }}
  labels:
    {{- include "firewall.gateway.labels" . | nindent 4 }}
  {{- with .Values.firewall.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
