{{- if .Values.firewall.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: firewall
  labels:
    {{- include "firewall.labels" . | nindent 4 }}
  {{- $negAnnotations := include "neuraltrust-platform.service.negAnnotations" (dict "global" .Values.global "backendConfigName" "firewall-backendconfig" "pscServiceKey" "firewall") }}
  {{- if $negAnnotations }}
  annotations:
    {{- $negAnnotations | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "firewall.selectorLabels" . | nindent 4 }}
  ports:
  - port: 80
    targetPort: http
    name: http
{{- end }}
