{{- /*
Create ClickHouse secret if it doesn't exist when existingSecret is configured
The ClickHouse chart expects this secret to exist when auth.existingSecret is set
*/}}
{{- if and .Values.clickhouse .Values.clickhouse.auth .Values.clickhouse.auth.existingSecret }}
{{- $secretName := .Values.clickhouse.auth.existingSecret }}
{{- $secretKey := .Values.clickhouse.auth.existingSecretKey | default "admin-password" }}
{{- /* Check preserveExistingSecrets flag - if true, skip secret creation (secrets are pre-generated) */}}
{{- $preserveSecrets := false }}
{{- if and .Values.global .Values.global.preserveExistingSecrets }}
  {{- $preserveSecrets = .Values.global.preserveExistingSecrets }}
{{- end }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- /* Create/update secret if preserveExistingSecrets is false */}}
{{- /* When preserveExistingSecrets: false, Helm will create or update the secret */}}
{{- /* When preserveExistingSecrets: true, skip entirely (secrets are pre-generated) */}}
{{- if not $preserveSecrets }}
{{- /* Resolve password: explicit value > existing in cluster > generate new */}}
{{- $password := "" }}
{{- if and .Values.clickhouse.auth.password (ne .Values.clickhouse.auth.password "") }}
  {{- $password = .Values.clickhouse.auth.password }}
{{- else if and $existingSecret $existingSecret.data (hasKey $existingSecret.data $secretKey) }}
  {{- /* Preserve existing password from cluster to avoid regenerating on each upgrade */}}
  {{- $password = index $existingSecret.data $secretKey | b64dec }}
{{- else }}
  {{- /* Generate a random password if not provided and doesn't exist yet */}}
  {{- $password = randAlphaNum 32 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "neuraltrust-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: clickhouse
type: Opaque
data:
  {{ $secretKey }}: {{ $password | b64enc }}
{{- end }}
{{- end }}
