{{- /*
Create ClickHouse secret if it doesn't exist when existingSecret is configured
The ClickHouse chart expects this secret to exist when auth.existingSecret is set
*/}}
{{- if and .Values.clickhouse .Values.clickhouse.auth .Values.clickhouse.auth.existingSecret }}
{{- $secretName := .Values.clickhouse.auth.existingSecret }}
{{- $secretKey := .Values.clickhouse.auth.existingSecretKey | default "admin-password" }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if not $existingSecret }}
{{- /* Secret doesn't exist, create it from values or generate a password */}}
{{- $password := "" }}
{{- if and .Values.clickhouse.auth.password (ne .Values.clickhouse.auth.password "") }}
  {{- $password = .Values.clickhouse.auth.password }}
{{- else }}
  {{- /* Generate a random password if not provided */}}
  {{- $password = randAlphaNum 32 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "neuraltrust-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: clickhouse
type: Opaque
data:
  {{ $secretKey }}: {{ $password | b64enc }}
{{- end }}
{{- end }}
