{{- if eq (include "neuraltrust-platform.kafka.useExternal" .) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-connection
  labels:
    {{- include "neuraltrust-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ include "neuraltrust-platform.kafka.bootstrapServers" . | quote }}
  {{- $protocol := include "neuraltrust-platform.kafka.securityProtocol" . }}
  {{- if ne $protocol "PLAINTEXT" }}
  KAFKA_SECURITY_PROTOCOL: {{ $protocol | quote }}
  {{- end }}
  {{- $auth := include "neuraltrust-platform.kafka.authConfig" . | fromYaml }}
  {{- if $auth.enabled }}
  KAFKA_SASL_MECHANISM: {{ $auth.mechanism | quote }}
  {{- end }}
  {{- $tls := include "neuraltrust-platform.kafka.tlsConfig" . | fromYaml }}
  {{- if $tls.enabled }}
  KAFKA_SSL_CA_LOCATION: {{ $tls.mountPath | quote }}
  {{- end }}
{{- end }}
