{{- /*
Platform Secrets Auto-Generation
=================================
Generates required secrets automatically when not explicitly provided in helm values.
Centralizes secret creation in the parent chart to coordinate shared values
(e.g., SERVER_SECRET_KEY and trustgateJwtSecret must be identical).

For each secret value, resolution order:
  1. Use explicitly provided value (non-empty string in helm values)
  2. Reuse value from existing Kubernetes Secret in the cluster (via lookup)
  3. Generate a new random value

Controlled by:
  - global.autoGenerateSecrets: true (default) → enables auto-generation from parent chart
  - global.autoGenerateSecrets: false → disables; subcharts manage their own secrets
  - global.preserveExistingSecrets: true → skips ALL secret creation entirely

NOTE: When using secret references (map values like {secretName: "x", secretKey: "y"}),
      set global.autoGenerateSecrets: false to let subchart templates handle them.
*/}}

{{- $autoGenerate := include "neuraltrust-platform.autoGenerateSecrets" . }}
{{- $preserveSecrets := false }}
{{- if and .Values.global .Values.global.preserveExistingSecrets }}
  {{- $preserveSecrets = true }}
{{- end }}

{{- if and $autoGenerate (not $preserveSecrets) }}

{{- /* ================================================================ */}}
{{- /* LOOKUP EXISTING SECRETS FROM CLUSTER                            */}}
{{- /* On first install these will be nil; on upgrades they preserve   */}}
{{- /* previously generated values.                                    */}}
{{- /* ================================================================ */}}

{{- $existingTrustgate := (lookup "v1" "Secret" .Release.Namespace "trustgate-secrets") }}
{{- $existingControlPlane := (lookup "v1" "Secret" .Release.Namespace "control-plane-secrets") }}
{{- $dpSecretName := "data-plane-jwt-secret" }}
{{- $dp := index .Values "neuraltrust-data-plane" }}
{{- if and $dp $dp.dataPlane $dp.dataPlane.secrets $dp.dataPlane.secrets.dataPlaneJWTSecretName (ne $dp.dataPlane.secrets.dataPlaneJWTSecretName "") }}
  {{- $dpSecretName = $dp.dataPlane.secrets.dataPlaneJWTSecretName }}
{{- end }}
{{- $existingDataPlane := (lookup "v1" "Secret" .Release.Namespace $dpSecretName) }}
{{- $existingPostgresql := (lookup "v1" "Secret" .Release.Namespace "postgresql-secrets") }}

{{- /* ================================================================ */}}
{{- /* RESOLVE SECRET VALUES                                           */}}
{{- /* explicit value > existing cluster value > auto-generate          */}}
{{- /* ================================================================ */}}

{{- /* --- Subchart value shortcuts --- */}}
{{- $tg := .Values.trustgate | default dict }}
{{- $tgGlobal := ($tg.global | default dict) }}
{{- $tgEnv := ($tgGlobal.env | default dict) }}
{{- $cp := index .Values "neuraltrust-control-plane" }}
{{- $cpSecrets := dict }}
{{- if and $cp $cp.controlPlane $cp.controlPlane.secrets }}
  {{- $cpSecrets = $cp.controlPlane.secrets }}
{{- end }}
{{- $cpPg := dict }}
{{- if and $cp $cp.controlPlane $cp.controlPlane.components $cp.controlPlane.components.postgresql $cp.controlPlane.components.postgresql.secrets }}
  {{- $cpPg = $cp.controlPlane.components.postgresql.secrets }}
{{- end }}
{{- $dpSecrets := dict }}
{{- if and $dp $dp.dataPlane $dp.dataPlane.secrets }}
  {{- $dpSecrets = $dp.dataPlane.secrets }}
{{- end }}

{{- /* ---------------------------------------------------------------- */}}
{{- /* Shared TrustGate Key (SERVER_SECRET_KEY = trustgateJwtSecret)    */}}
{{- /* This value MUST be identical in trustgate-secrets and            */}}
{{- /* control-plane-secrets. Resolve once, use in both.                */}}
{{- /* ---------------------------------------------------------------- */}}

{{- $trustgateSharedKey := "" }}
{{- /* Check explicit value from trustgate.global.env.SERVER_SECRET_KEY */}}
{{- if and (hasKey $tgEnv "SERVER_SECRET_KEY") $tgEnv.SERVER_SECRET_KEY (ne $tgEnv.SERVER_SECRET_KEY "") }}
  {{- $trustgateSharedKey = $tgEnv.SERVER_SECRET_KEY }}
{{- end }}
{{- /* Check explicit value from control-plane trustgateJwtSecret */}}
{{- if not $trustgateSharedKey }}
  {{- if and (hasKey $cpSecrets "trustgateJwtSecret") $cpSecrets.trustgateJwtSecret (ne ($cpSecrets.trustgateJwtSecret | toString) "") }}
    {{- $trustgateSharedKey = $cpSecrets.trustgateJwtSecret | toString }}
  {{- end }}
{{- end }}
{{- /* Check existing cluster secrets */}}
{{- if not $trustgateSharedKey }}
  {{- if and $existingTrustgate (kindIs "map" $existingTrustgate) }}
    {{- if and (index $existingTrustgate "data") (hasKey $existingTrustgate.data "SERVER_SECRET_KEY") }}
      {{- $trustgateSharedKey = index $existingTrustgate.data "SERVER_SECRET_KEY" | b64dec }}
    {{- end }}
  {{- end }}
{{- end }}
{{- if not $trustgateSharedKey }}
  {{- if and $existingControlPlane (kindIs "map" $existingControlPlane) }}
    {{- if and (index $existingControlPlane "data") (hasKey $existingControlPlane.data "TRUSTGATE_JWT_SECRET") }}
      {{- $trustgateSharedKey = index $existingControlPlane.data "TRUSTGATE_JWT_SECRET" | b64dec }}
    {{- end }}
  {{- end }}
{{- end }}
{{- /* Generate if still empty */}}
{{- if not $trustgateSharedKey }}
  {{- $trustgateSharedKey = randAlphaNum 64 }}
{{- end }}

{{- /* ---------------------------------------------------------------- */}}
{{- /* Control Plane JWT Secret                                         */}}
{{- /* ---------------------------------------------------------------- */}}
{{- $cpJwtSecret := include "neuraltrust-platform.resolveSecret" (dict "value" ($cpSecrets.controlPlaneJWTSecret | default "") "existingSecret" $existingControlPlane "secretKey" "CONTROL_PLANE_JWT_SECRET" "length" 64) }}

{{- /* ---------------------------------------------------------------- */}}
{{- /* Data Plane JWT Secret                                            */}}
{{- /* ---------------------------------------------------------------- */}}
{{- $dpJwtSecret := include "neuraltrust-platform.resolveSecret" (dict "value" ($dpSecrets.dataPlaneJWTSecret | default "") "existingSecret" $existingDataPlane "secretKey" "DATA_PLANE_JWT_SECRET" "length" 64) }}

{{- /* ---------------------------------------------------------------- */}}
{{- /* PostgreSQL Password                                              */}}
{{- /* ---------------------------------------------------------------- */}}
{{- $pgPassword := include "neuraltrust-platform.resolveSecret" (dict "value" ($cpPg.password | default "") "existingSecret" $existingPostgresql "secretKey" "POSTGRES_PASSWORD" "length" 32) }}

{{- /* ---------------------------------------------------------------- */}}
{{- /* TrustGate Database Password                                      */}}
{{- /* ---------------------------------------------------------------- */}}
{{- $tgDbPassword := include "neuraltrust-platform.resolveSecret" (dict "value" ($tgEnv.DATABASE_PASSWORD | default "") "existingSecret" $existingTrustgate "secretKey" "DATABASE_PASSWORD" "length" 32) }}

{{- /* ---------------------------------------------------------------- */}}
{{- /* TrustGate Database Connection Values                             */}}
{{- /* ---------------------------------------------------------------- */}}
{{- $tgDbHost := $tgEnv.DATABASE_HOST | default "control-plane-postgresql" }}
{{- $tgDbPort := $tgEnv.DATABASE_PORT | default "5432" | toString }}
{{- $tgDbUser := $tgEnv.DATABASE_USER | default "trustgate" }}
{{- $tgDbName := $tgEnv.DATABASE_NAME | default "trustgate" }}
{{- $tgDbSslMode := $tgEnv.DATABASE_SSL_MODE | default "disable" }}
{{- $tgDbUrl := printf "postgresql://%s:%s@%s:%s/%s?sslmode=%s" $tgDbUser ($tgDbPassword | urlquery) $tgDbHost $tgDbPort $tgDbName $tgDbSslMode }}

{{- /* ---------------------------------------------------------------- */}}
{{- /* PostgreSQL Connection Values                                     */}}
{{- /* ---------------------------------------------------------------- */}}
{{- $pgUser := $cpPg.user | default "neuraltrust" }}
{{- $pgDb := $cpPg.database | default "neuraltrust" }}
{{- $pgHost := $cpPg.host | default "control-plane-postgresql" }}
{{- $pgPort := $cpPg.port | default "5432" | toString }}
{{- $pgSslMode := "require" }}
{{- if and $cp $cp.infrastructure $cp.infrastructure.postgresql (hasKey $cp.infrastructure.postgresql "deploy") }}
  {{- if $cp.infrastructure.postgresql.deploy }}
    {{- $pgSslMode = "disable" }}
  {{- end }}
{{- end }}
{{- $pgDbUrl := printf "postgresql://%s:%s@%s:%s/%s?connection_limit=15&sslmode=%s" $pgUser ($pgPassword | urlquery) $pgHost $pgPort $pgDb $pgSslMode }}

{{- /* ---------------------------------------------------------------- */}}
{{- /* Control Plane Optional Secrets (not auto-generated)              */}}
{{- /* ---------------------------------------------------------------- */}}
{{- $cpOpenaiKey := $cpSecrets.openaiApiKey | default "" }}
{{- $cpResendKey := $cpSecrets.resendApiKey | default "" }}
{{- $cpResendAlert := $cpSecrets.resendAlertSender | default "" }}
{{- $cpResendInvite := $cpSecrets.resendInviteSender | default "" }}
{{- $cpFirewallJwt := $cpSecrets.firewallJwtSecret | default "" }}
{{- $cpModelScanner := $cpSecrets.modelScannerSecret | default "" }}


{{- /* ================================================================ */}}
{{- /* CREATE KUBERNETES SECRETS                                        */}}
{{- /* ================================================================ */}}


{{- /* ================================================================ */}}
{{- /* 1. TRUSTGATE SECRETS                                             */}}
{{- /* ================================================================ */}}
{{- if and .Values.trustgate .Values.trustgate.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: trustgate-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
  labels:
    app.kubernetes.io/name: {{ include "neuraltrust-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: trustgate
type: Opaque
data:
  DATABASE_HOST: {{ $tgDbHost | b64enc | quote }}
  DATABASE_PORT: {{ $tgDbPort | b64enc | quote }}
  DATABASE_USER: {{ $tgDbUser | b64enc | quote }}
  DATABASE_PASSWORD: {{ $tgDbPassword | b64enc | quote }}
  DATABASE_NAME: {{ $tgDbName | b64enc | quote }}
  DATABASE_SSL_MODE: {{ $tgDbSslMode | b64enc | quote }}
  DATABASE_URL: {{ $tgDbUrl | b64enc | quote }}
  SERVER_SECRET_KEY: {{ $trustgateSharedKey | b64enc | quote }}
  {{- if and .Values.trustgate .Values.trustgate.config .Values.trustgate.config.providers }}
  {{- range $provider, $config := .Values.trustgate.config.providers }}
  {{- if $config.apiKey }}
  {{ $provider }}-api-key: {{ $config.apiKey | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}

---
{{- /* ================================================================ */}}
{{- /* 2. CONTROL PLANE SECRETS                                         */}}
{{- /* ================================================================ */}}
{{- $cpEnabled := false }}
{{- if and $cp $cp.controlPlane $cp.controlPlane.enabled }}
  {{- $cpEnabled = true }}
{{- end }}
{{- if $cpEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: control-plane-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "neuraltrust-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: control-plane
type: Opaque
data:
  CONTROL_PLANE_JWT_SECRET: {{ $cpJwtSecret | b64enc }}
  OPENAI_API_KEY: {{ $cpOpenaiKey | b64enc | quote }}
  resend-api-key: {{ $cpResendKey | b64enc | quote }}
  resend-alert-sender: {{ $cpResendAlert | b64enc | quote }}
  resend-invite-sender: {{ $cpResendInvite | b64enc | quote }}
  TRUSTGATE_JWT_SECRET: {{ $trustgateSharedKey | b64enc }}
  {{- if and $cpFirewallJwt (ne $cpFirewallJwt "") }}
  FIREWALL_JWT_SECRET: {{ $cpFirewallJwt | b64enc }}
  {{- end }}
  MODEL_SCANNER_SECRET: {{ $cpModelScanner | b64enc | quote }}
{{- end }}

---
{{- /* ================================================================ */}}
{{- /* 3. DATA PLANE JWT SECRET                                         */}}
{{- /* ================================================================ */}}
{{- $dpEnabled := false }}
{{- if and $dp $dp.dataPlane $dp.dataPlane.enabled }}
  {{- $dpEnabled = true }}
{{- end }}
{{- if $dpEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $dpSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "neuraltrust-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: data-plane
type: Opaque
data:
  DATA_PLANE_JWT_SECRET: {{ $dpJwtSecret | b64enc }}
{{- end }}

---
{{- /* ================================================================ */}}
{{- /* 4. POSTGRESQL SECRETS                                            */}}
{{- /* ================================================================ */}}
{{- $pgDeploy := false }}
{{- if and $cp $cp.infrastructure $cp.infrastructure.postgresql (hasKey $cp.infrastructure.postgresql "deploy") }}
  {{- $pgDeploy = $cp.infrastructure.postgresql.deploy }}
{{- end }}
{{- /* Create postgresql-secrets if PostgreSQL is deployed OR if password/host is configured */}}
{{- if or $pgDeploy $pgPassword $pgHost }}
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "neuraltrust-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  POSTGRES_USER: {{ $pgUser | b64enc }}
  POSTGRES_PASSWORD: {{ $pgPassword | b64enc }}
  POSTGRES_DB: {{ $pgDb | b64enc }}
  POSTGRES_HOST: {{ $pgHost | b64enc }}
  POSTGRES_PORT: {{ $pgPort | b64enc }}
  DATABASE_URL: {{ $pgDbUrl | b64enc }}
  POSTGRES_PRISMA_URL: {{ $pgDbUrl | b64enc }}
{{- end }}

{{- end }}
{{- /* End of autoGenerate && !preserveSecrets */}}
