#!/usr/bin/env bash
# scripts/export-controlplane-ca.sh
#
# Collect the CA certificates a remote data plane needs to trust a customer-owned
# control plane (global.deploymentMode=saas), and emit them as one Secret.
#
# Only relevant when the control plane serves chart-generated certificates. With
# a certificate your data planes already trust — publicly trusted, or issued by
# your own PKI — there is nothing to export.
#
# Each component mints its own CA, so a data plane needs all of them. Rather than
# copy three or four secrets by hand, this bundles every CA into a single
# ca.crt (Go and the OpenTelemetry Collector both accept concatenated PEM).
#
# Usage:
#   ./scripts/export-controlplane-ca.sh [-n NAMESPACE] [-o OUTPUT] [--name SECRET]
#
#   -n, --namespace   control-plane namespace (default: neuraltrust)
#   -o, --output      write here instead of stdout
#       --name        name of the emitted Secret (default: controlplane-ca)
#       --context     kubectl context of the control-plane cluster
#
# Apply the result in every remote data-plane cluster, then point the three
# dialling legs at it:
#
#   global:
#     customCaCert:
#       enabled: true
#       secretName: controlplane-ca        # DataAgent + config-sync read the file
#     clickstack:
#       egress:
#         tlsCaSecretName: controlplane-ca # collector reads its own trust store
#   dataagent:
#     databridge:
#       tlsCa: /etc/ssl/certs/custom-ca.crt
#   agentgateway:
#     configSync:
#       tlsCa: /etc/ssl/certs/custom-ca.crt
#   trustguard:
#     configSync:
#       tlsCa: /etc/ssl/certs/custom-ca.crt

set -euo pipefail

NAMESPACE="neuraltrust"
OUTPUT=""
SECRET_NAME="controlplane-ca"
KUBE_CONTEXT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    -n|--namespace) NAMESPACE="$2"; shift 2 ;;
    -o|--output) OUTPUT="$2"; shift 2 ;;
    --name) SECRET_NAME="$2"; shift 2 ;;
    --context) KUBE_CONTEXT="$2"; shift 2 ;;
    -h|--help) sed -n '2,40p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

for tool in kubectl base64; do
  command -v "$tool" >/dev/null 2>&1 || { echo "error: $tool not found in PATH" >&2; exit 1; }
done

kube() {
  if [[ -n "$KUBE_CONTEXT" ]]; then
    kubectl --context "$KUBE_CONTEXT" "$@"
  else
    kubectl "$@"
  fi
}

# GNU coreutils decodes with -d, BSD/macOS with -D. Probe once: falling back
# mid-pipeline would lose the input the failed attempt already consumed.
if base64 -d </dev/null >/dev/null 2>&1; then
  B64_DECODE=(base64 -d)
else
  B64_DECODE=(base64 -D)
fi

# The components that terminate TLS for a remote caller. Labelled by the chart,
# so this keeps working through nameOverride and release renames.
COMPONENTS="southbound-tls,configsync-tls,telemetry-ingress-tls"

# Read into an array without mapfile, which needs bash 4 (macOS ships 3.2).
secrets=()
while IFS= read -r line; do
  [[ -n "$line" ]] && secrets+=("$line")
done < <(
  kube get secrets -n "$NAMESPACE" \
    -l "app.kubernetes.io/component in ($COMPONENTS)" \
    -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' 2>/dev/null
)

if [[ ${#secrets[@]} -eq 0 ]]; then
  cat >&2 <<EOF
error: no chart-generated TLS secrets found in namespace "$NAMESPACE".

Either the control plane is not running here, or it serves certificates you
supplied yourself. In the second case there is nothing to export: distribute
whatever CA signed those certificates instead.
EOF
  exit 1
fi

bundle=""
included=()
skipped=()

for secret in "${secrets[@]}"; do
  ca="$(kube get secret "$secret" -n "$NAMESPACE" -o jsonpath='{.data.ca\.crt}' 2>/dev/null || true)"
  if [[ -z "$ca" ]]; then
    # An operator-supplied or cert-manager secret need not carry ca.crt.
    skipped+=("$secret")
    continue
  fi
  pem="$(printf '%s' "$ca" | "${B64_DECODE[@]}")"
  # A bundle of garbage fails at handshake time in another cluster, a long way
  # from here, so refuse to carry anything that is not a parseable certificate.
  if ! printf '%s\n' "$pem" | openssl x509 -noout >/dev/null 2>&1; then
    echo "error: ca.crt in secret \"$secret\" is not a valid PEM certificate." >&2
    echo "       Refusing to write a bundle the remote clusters would reject." >&2
    exit 1
  fi
  # Same CA reused across components (your own PKI, one cert-manager issuer)
  # would otherwise land in the bundle several times.
  if [[ "$bundle" == *"$pem"* ]]; then
    continue
  fi
  bundle+="$pem"
  [[ "$pem" == *$'\n' ]] || bundle+=$'\n'
  included+=("$secret")
done

if [[ -z "$bundle" ]]; then
  echo "error: found ${#secrets[@]} TLS secret(s) but none carried a ca.crt key." >&2
  echo "       Those certificates were not generated by the chart; distribute their CA yourself." >&2
  exit 1
fi

encoded="$(printf '%s' "$bundle" | base64 | tr -d '\n')"

manifest="$(cat <<EOF
# Generated by scripts/export-controlplane-ca.sh from namespace "$NAMESPACE".
# Apply in each remote data-plane cluster, in the namespace the data plane runs in.
apiVersion: v1
kind: Secret
metadata:
  name: $SECRET_NAME
  labels:
    app.kubernetes.io/part-of: neuraltrust-platform
    app.kubernetes.io/component: controlplane-ca
type: Opaque
data:
  ca.crt: $encoded
EOF
)"

if [[ -n "$OUTPUT" ]]; then
  printf '%s\n' "$manifest" > "$OUTPUT"
  echo "wrote $OUTPUT" >&2
else
  printf '%s\n' "$manifest"
fi

echo "bundled ${#included[@]} CA certificate(s) from: ${included[*]}" >&2
if [[ ${#skipped[@]} -gt 0 ]]; then
  echo "no ca.crt (not chart-generated), skipped: ${skipped[*]}" >&2
fi
