{{- if and .Values.aispm.enabled .Values.aispm.api.autoscaling .Values.aispm.api.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aispm-api
  labels:
    {{- include "aispm.labels" (dict "component" "api" "context" .) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aispm-api
  minReplicas: {{ .Values.aispm.api.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ .Values.aispm.api.autoscaling.maxReplicas | default 4 }}
  metrics:
    {{- if .Values.aispm.api.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.aispm.api.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.aispm.api.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.aispm.api.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
