{{- if and .Values.aispm.enabled .Values.aispm.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.aispm.serviceAccount.name | default "aispm" }}
  labels:
    {{- include "aispm.labels" (dict "component" "api" "context" .) | nindent 4 }}
  {{- $saAnn := include "neuraltrust-platform.serviceAccount.annotationsBlock" (dict "ctx" . "annotations" .Values.aispm.serviceAccount.annotations) }}
  {{- with $saAnn }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
