{{- if and (eq (include "trustguard.enabled" .) "true") (eq (include "neuraltrust-platform.isFull" .) "true") }}
{{- $as := default dict .Values.controlPlane.autoscaling }}
{{- if $as.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.controlPlane.name }}
  labels:
    {{- include "trustguard.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.controlPlane.name }}
  minReplicas: {{ default 1 $as.minReplicas }}
  maxReplicas: {{ default 3 $as.maxReplicas }}
  metrics:
    {{- if $as.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $as.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $as.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $as.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
